name: rajaongkir_api
description: A flutter app for estimated shipping cost with Rajaongkir API for Flutter Framework and Dart Programming  Language
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  http: ^0.13.4
  intl: ^0.17.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
